
CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE NOT NULL,
    discount_type VARCHAR(50) NOT NULL, -- e.g., 'FIXED' or 'PERCENTAGE'
    discount_value DECIMAL(10, 2) NOT NULL,
    expiration_date TIMESTAMPTZ,
    max_uses INT,
    times_used INT DEFAULT 0,
    min_purchase_amount DECIMAL(10, 2),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE orders
ADD COLUMN coupon_id BIGINT,
ADD CONSTRAINT fk_coupon
    FOREIGN KEY(coupon_id) 
    REFERENCES coupons(id);

-- Insert coupon seed data
INSERT INTO coupons (id, code, discount_type, discount_value, expiration_date, max_uses, times_used, min_purchase_amount, is_active, created_at, updated_at) VALUES
(1, 'FIXED10', 'FIXED', 10.00, '2025-11-30 00:00:00+00', NULL, 0, NULL, true, '2025-11-09 18:32:34.751901+00', '2025-11-09 18:32:34.751918+00'),
(2, 'PER20', 'PERCENTAGE', 20.00, '2025-11-30 00:00:00+00', NULL, 1, NULL, true, '2025-11-09 18:33:02.133743+00', '2025-11-09 18:48:02.793639+00'),
(3, 'TESTACT', 'FIXED', 60.00, '2025-11-30 00:00:00+00', NULL, 0, NULL, false, '2025-11-09 18:35:44.541049+00', '2025-11-09 18:35:44.541091+00'),
(4, 'TESTMIN', 'FIXED', 2500.00, '2025-11-30 00:00:00+00', NULL, 0, 3000.00, true, '2025-11-09 18:36:22.55234+00', '2025-11-09 18:36:22.552356+00'),
(5, 'CLOSE7', 'FIXED', 80.00, '2025-11-16 00:00:00+00', NULL, 0, NULL, true, '2025-11-09 18:37:11.841809+00', '2025-11-09 18:37:11.841819+00'),
(6, 'TESTLIM', 'FIXED', 80.00, '2025-11-30 00:00:00+00', 1, 1, NULL, true, '2025-11-09 18:38:08.920158+00', '2025-11-09 18:39:52.018418+00'),
(7, 'TESTDATE', 'FIXED', 1000.00, '2025-11-06 00:00:00+00', NULL, 0, NULL, true, '2025-11-09 18:38:51.493063+00', '2025-11-09 18:38:51.493072+00');

-- Update the sequence to match the max ID (7)
SELECT setval('coupons_id_seq', 7);

