--
-- PostgreSQL database dump
--

\restrict 9xTYdmW61eSbNBYigsi1vWrKDk6Kmx9KjUq2ty8KkRivfar4CwQTWbIeBLFRHyx

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 15.14

-- Started on 2025-10-17 04:06:02 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16386)
-- Name: categories; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.categories OWNER TO myuser;

--
-- TOC entry 214 (class 1259 OID 16385)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16392)
-- Name: order_items; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    price double precision,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.order_items OWNER TO myuser;

--
-- TOC entry 216 (class 1259 OID 16391)
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16398)
-- Name: orders; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    order_date timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    total_price double precision,
    customer_id bigint NOT NULL,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO myuser;

--
-- TOC entry 218 (class 1259 OID 16397)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16405)
-- Name: payments; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount double precision,
    payment_date timestamp(6) without time zone,
    status character varying(255),
    order_id bigint NOT NULL,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO myuser;

--
-- TOC entry 220 (class 1259 OID 16404)
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16412)
-- Name: products; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    description character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price double precision,
    size character varying(255),
    stock integer,
    category_id bigint,
    seller_id bigint NOT NULL
);


ALTER TABLE public.products OWNER TO myuser;

--
-- TOC entry 222 (class 1259 OID 16411)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16420)
-- Name: users; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'SELLER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO myuser;

--
-- TOC entry 224 (class 1259 OID 16419)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3458 (class 0 OID 16386)
-- Dependencies: 215
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.categories (id, name) FROM stdin;
1	shoe
\.


--
-- TOC entry 3460 (class 0 OID 16392)
-- Dependencies: 217
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.order_items (id, price, quantity, order_id, product_id) FROM stdin;
\.


--
-- TOC entry 3462 (class 0 OID 16398)
-- Dependencies: 219
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.orders (id, order_date, status, total_price, customer_id) FROM stdin;
7	2025-10-17 00:02:15.509688	DELIVERED	999	1
8	2025-10-17 00:06:55.974884	CANCELED	999	1
\.


--
-- TOC entry 3464 (class 0 OID 16405)
-- Dependencies: 221
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.payments (id, amount, payment_date, status, order_id) FROM stdin;
\.


--
-- TOC entry 3466 (class 0 OID 16412)
-- Dependencies: 223
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.products (id, description, image_url, name, price, size, stock, category_id, seller_id) FROM stdin;
107	Sample shoe product 1	/uploads/images/default-product.svg	Shoe Model 1	111111	42	11111110	1	34
108	Sample shoe product 2	/uploads/images/default-product.svg	Shoe Model 2	2222	39	22205	1	34
115	Limited edition colorful Nike shoe from 1998	/uploads/images/nike-shoe-1998.jpg	Nike Shoe 1998 Limited Edition	4500	45	20	1	34
\.


--
-- TOC entry 3468 (class 0 OID 16420)
-- Dependencies: 225
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: myuser
--

COPY public.users (user_id, password, role, username) FROM stdin;
1	$2a$10$aJ6BwRdeQDgiRXS/ewgA5eea66Ol89inDngJYAeg8e0nnodmAPiVC	CUSTOMER	customer@customer.com
34	$2a$10$CxTNXiDZq81M50wtuG6XcucBtuE7PpPweCatB9/yLVXSOooCaYFrW	ADMIN	admin@admin.com
\.


--
-- TOC entry 3474 (class 0 OID 0)
-- Dependencies: 214
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, true);


--
-- TOC entry 3475 (class 0 OID 0)
-- Dependencies: 216
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.order_items_id_seq', 8, true);


--
-- TOC entry 3476 (class 0 OID 0)
-- Dependencies: 218
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.orders_id_seq', 8, true);


--
-- TOC entry 3477 (class 0 OID 0)
-- Dependencies: 220
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.payments_id_seq', 1, true);


--
-- TOC entry 3478 (class 0 OID 0)
-- Dependencies: 222
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.products_id_seq', 115, true);


--
-- TOC entry 3479 (class 0 OID 0)
-- Dependencies: 224
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.users_user_id_seq', 34, true);


--
-- TOC entry 3292 (class 2606 OID 16390)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3296 (class 2606 OID 16396)
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3298 (class 2606 OID 16403)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 3300 (class 2606 OID 16410)
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- TOC entry 3304 (class 2606 OID 16418)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3302 (class 2606 OID 16431)
-- Name: payments uk8vo36cen604as7etdfwmyjsxt; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk8vo36cen604as7etdfwmyjsxt UNIQUE (order_id);


--
-- TOC entry 3306 (class 2606 OID 16433)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 3294 (class 2606 OID 16429)
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- TOC entry 3308 (class 2606 OID 16427)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 3312 (class 2606 OID 16449)
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- TOC entry 3313 (class 2606 OID 16459)
-- Name: products fkbgw3lyxhsml3kfqnfr45o0vbj; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkbgw3lyxhsml3kfqnfr45o0vbj FOREIGN KEY (seller_id) REFERENCES public.users(user_id);


--
-- TOC entry 3309 (class 2606 OID 16434)
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- TOC entry 3310 (class 2606 OID 16439)
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 3314 (class 2606 OID 16454)
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- TOC entry 3311 (class 2606 OID 16444)
-- Name: orders fksjfs85qf6vmcurlx43cnc16gy; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fksjfs85qf6vmcurlx43cnc16gy FOREIGN KEY (customer_id) REFERENCES public.users(user_id);


-- Completed on 2025-10-17 04:06:02 UTC

--
-- PostgreSQL database dump complete
--

\unrestrict 9xTYdmW61eSbNBYigsi1vWrKDk6Kmx9KjUq2ty8KkRivfar4CwQTWbIeBLFRHyx

