--
-- PostgreSQL database dump
--

\restrict eqO9Bk7MphNeI75LdrD69bcvmR2dUOCq98aI31euPzOuEaqIW7Ip0iXabkHoWYn

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 15.14 (Debian 15.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.orders DROP CONSTRAINT IF EXISTS fk_coupon;
DROP INDEX IF EXISTS public.flyway_schema_history_s_idx;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.products DROP CONSTRAINT IF EXISTS products_pkey;
ALTER TABLE IF EXISTS ONLY public.payments DROP CONSTRAINT IF EXISTS payments_pkey;
ALTER TABLE IF EXISTS ONLY public.orders DROP CONSTRAINT IF EXISTS orders_pkey;
ALTER TABLE IF EXISTS ONLY public.order_items DROP CONSTRAINT IF EXISTS order_items_pkey;
ALTER TABLE IF EXISTS ONLY public.flyway_schema_history DROP CONSTRAINT IF EXISTS flyway_schema_history_pk;
ALTER TABLE IF EXISTS ONLY public.coupons DROP CONSTRAINT IF EXISTS coupons_pkey;
ALTER TABLE IF EXISTS ONLY public.coupons DROP CONSTRAINT IF EXISTS coupons_code_key;
ALTER TABLE IF EXISTS ONLY public.categories DROP CONSTRAINT IF EXISTS categories_pkey;
ALTER TABLE IF EXISTS public.coupons ALTER COLUMN id DROP DEFAULT;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.products;
DROP TABLE IF EXISTS public.payments;
DROP TABLE IF EXISTS public.orders;
DROP TABLE IF EXISTS public.order_items;
DROP TABLE IF EXISTS public.flyway_schema_history;
DROP SEQUENCE IF EXISTS public.coupons_id_seq;
DROP TABLE IF EXISTS public.coupons;
DROP TABLE IF EXISTS public.categories;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.categories OWNER TO myuser;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    discount_type character varying(50) NOT NULL,
    discount_value numeric(10,2) NOT NULL,
    expiration_date timestamp with time zone,
    max_uses integer,
    times_used integer DEFAULT 0,
    min_purchase_amount numeric(10,2),
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.coupons OWNER TO myuser;

--
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO myuser;

--
-- Name: order_items; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    price double precision,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.order_items OWNER TO myuser;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    order_date timestamp without time zone NOT NULL,
    status character varying(255) NOT NULL,
    total_price double precision,
    customer_id bigint NOT NULL,
    coupon_id bigint
);


ALTER TABLE public.orders OWNER TO myuser;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount double precision,
    payment_date timestamp without time zone,
    status character varying(255),
    order_id bigint NOT NULL
);


ALTER TABLE public.payments OWNER TO myuser;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    description character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price double precision,
    size character varying(255),
    stock integer,
    category_id bigint,
    seller_id bigint NOT NULL
);


ALTER TABLE public.products OWNER TO myuser;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO myuser;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: myuser
--

INSERT INTO public.categories (id, name) VALUES (1, 'Nike');
INSERT INTO public.categories (id, name) VALUES (2, 'Puma');


--
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: myuser
--

INSERT INTO public.coupons (id, code, discount_type, discount_value, expiration_date, max_uses, times_used, min_purchase_amount, is_active, created_at, updated_at) VALUES (1, 'FIXED10', 'FIXED', 10.00, '2025-11-30 00:00:00+00', NULL, 0, NULL, true, '2025-11-09 18:32:34.751901+00', '2025-11-09 18:32:34.751918+00');
INSERT INTO public.coupons (id, code, discount_type, discount_value, expiration_date, max_uses, times_used, min_purchase_amount, is_active, created_at, updated_at) VALUES (3, 'TESTACT', 'FIXED', 60.00, '2025-11-30 00:00:00+00', NULL, 0, NULL, false, '2025-11-09 18:35:44.541049+00', '2025-11-09 18:35:44.541091+00');
INSERT INTO public.coupons (id, code, discount_type, discount_value, expiration_date, max_uses, times_used, min_purchase_amount, is_active, created_at, updated_at) VALUES (4, 'TESTMIN', 'FIXED', 2500.00, '2025-11-30 00:00:00+00', NULL, 0, 3000.00, true, '2025-11-09 18:36:22.55234+00', '2025-11-09 18:36:22.552356+00');
INSERT INTO public.coupons (id, code, discount_type, discount_value, expiration_date, max_uses, times_used, min_purchase_amount, is_active, created_at, updated_at) VALUES (5, 'CLOSE7', 'FIXED', 80.00, '2025-11-16 00:00:00+00', NULL, 0, NULL, true, '2025-11-09 18:37:11.841809+00', '2025-11-09 18:37:11.841819+00');
INSERT INTO public.coupons (id, code, discount_type, discount_value, expiration_date, max_uses, times_used, min_purchase_amount, is_active, created_at, updated_at) VALUES (7, 'TESTDATE', 'FIXED', 1000.00, '2025-11-06 00:00:00+00', NULL, 0, NULL, true, '2025-11-09 18:38:51.493063+00', '2025-11-09 18:38:51.493072+00');
INSERT INTO public.coupons (id, code, discount_type, discount_value, expiration_date, max_uses, times_used, min_purchase_amount, is_active, created_at, updated_at) VALUES (6, 'TESTLIM', 'FIXED', 80.00, '2025-11-30 00:00:00+00', 1, 1, NULL, true, '2025-11-09 18:38:08.920158+00', '2025-11-09 18:39:52.018418+00');
INSERT INTO public.coupons (id, code, discount_type, discount_value, expiration_date, max_uses, times_used, min_purchase_amount, is_active, created_at, updated_at) VALUES (2, 'PER20', 'PERCENTAGE', 20.00, '2025-11-30 00:00:00+00', NULL, 2, NULL, true, '2025-11-09 18:33:02.133743+00', '2025-11-12 18:59:15.635311+00');


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: myuser
--

INSERT INTO public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) VALUES (1, '1', 'init schema', 'SQL', 'V1__init_schema.sql', 513428178, 'myuser', '2025-11-12 18:46:32.421476', 71, true);
INSERT INTO public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) VALUES (2, '2', 'seed data', 'SQL', 'V2__seed_data.sql', -1279251362, 'myuser', '2025-11-12 18:46:32.531783', 9, true);
INSERT INTO public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) VALUES (3, '3', 'add coupons', 'SQL', 'V3__add_coupons.sql', -512680306, 'myuser', '2025-11-12 18:46:32.562018', 25, true);


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: myuser
--

INSERT INTO public.order_items (id, price, quantity, order_id, product_id) VALUES (1, 1800, 1, 1, 3);
INSERT INTO public.order_items (id, price, quantity, order_id, product_id) VALUES (2, 1800, 1, 1, 4);
INSERT INTO public.order_items (id, price, quantity, order_id, product_id) VALUES (3, 1800, 1, 2, 3);
INSERT INTO public.order_items (id, price, quantity, order_id, product_id) VALUES (4, 1800, 3, 3, 4);


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: myuser
--

INSERT INTO public.orders (id, order_date, status, total_price, customer_id, coupon_id) VALUES (1, '2025-11-12 18:58:37.224721', 'CANCELED', 3600, 1, NULL);
INSERT INTO public.orders (id, order_date, status, total_price, customer_id, coupon_id) VALUES (2, '2025-11-12 18:59:15.626777', 'DELIVERED', 1440, 1, 2);
INSERT INTO public.orders (id, order_date, status, total_price, customer_id, coupon_id) VALUES (3, '2025-11-12 19:00:45.412479', 'PENDING', 5400, 1, NULL);


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: myuser
--



--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: myuser
--

INSERT INTO public.products (id, description, image_url, name, price, size, stock, category_id, seller_id) VALUES (1, '', '/uploads/images/nike-air-force1.png', 'Nike Air Force1', 3500, '42', 5, 1, 2);
INSERT INTO public.products (id, description, image_url, name, price, size, stock, category_id, seller_id) VALUES (2, '', '/uploads/images/nike-shoe-1998-limited.jpg', 'Nike Shoe 1998 Limited Edition', 2000, '42', 10, 1, 2);
INSERT INTO public.products (id, description, image_url, name, price, size, stock, category_id, seller_id) VALUES (3, '', '/uploads/images/puma-shoe-alpha.png', 'Puma Shoe Alpha', 1800, '39', 0, 2, 2);
INSERT INTO public.products (id, description, image_url, name, price, size, stock, category_id, seller_id) VALUES (4, '', '/uploads/images/puma-x-travis.jpg', 'Puma X Travis', 1800, '39', 15, 2, 2);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: myuser
--

INSERT INTO public.users (user_id, password, role, username) VALUES (1, '$2a$10$XO.jCOhHz/jxwfLbK/wFZevv675r6CCPOfRY2S4A8Otrjbp9XcFLO', 'CUSTOMER', 'customer@customer.com');
INSERT INTO public.users (user_id, password, role, username) VALUES (2, '$2a$10$CxTNXiDZq81M50wtuG6XcucBtuE7PpPweCatB9/yLVXSOooCaYFrW', 'ADMIN', 'admin@admin.com');


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.categories_id_seq', 2, true);


--
-- Name: coupons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.coupons_id_seq', 7, true);


--
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.order_items_id_seq', 4, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.orders_id_seq', 3, true);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.payments_id_seq', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.products_id_seq', 4, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: myuser
--

SELECT pg_catalog.setval('public.users_user_id_seq', 2, true);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: coupons coupons_code_key; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_code_key UNIQUE (code);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: myuser
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: orders fk_coupon; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_coupon FOREIGN KEY (coupon_id) REFERENCES public.coupons(id);


--
-- PostgreSQL database dump complete
--

\unrestrict eqO9Bk7MphNeI75LdrD69bcvmR2dUOCq98aI31euPzOuEaqIW7Ip0iXabkHoWYn

